branch-defaults:
  master:
    environment: express-app-dev
    group_suffix: null
global:
  application_name: express_app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
