version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Check ~/.aws/config
          command: cat ~/.aws/config
      - run:
          name: "Check elasticbeanstalk config"
          command: |
            cat .elasticbeanstalk/config.yml
      - run:
          name: Deploy to EB
          command: |
            eb list
            eb use express-app-dev --profile eb-cli
            eb deploy -v --staged --profile eb-cli
 
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          context: TEST
          filters:
            branches:
              only:
                - master